<?php

$this->sections[] = array(
	'icon' => 'dashicons dashicons-editor-paragraph',
	'title' => esc_html__( 'Typography', 'engage' ),
	'heading' => esc_html__( 'Typography Settings', 'engage' ),
	'fields' => array(		
			
		array(
			'id' => 'section-start',
			'type' => 'section',
			'title' => esc_html__( 'Main Typography', 'engage' ),
			'indent' => true,
		),		
		array(
			'id' => 'body-font',
			'type' => 'typography',
			'title' => esc_html__( 'Body', 'engage' ),
			'google' => true,
			'text-align' => false,
			'line-height' => true,
			'letter-spacing' => true,
			'subsets' => false,
			'color' => false,
			'output' => array( 'body' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '14px',
				'font-weight' => '400',
				'letter-spacing' => '1px',
				'line-height' => '14px',
				'google' => true,
			),
		),
		array(
			'id' => 'p-font',
			'type' => 'typography',
			'title' => esc_html__( 'Paragraph font', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => true,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( 'p' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '20px',
				'letter-spacing' => '1px',
				'font-weight' => '400',
				'line-height' => '36px',
				'color'	=> '#707070',
				'google' => true,
			),
		),
		array(
			'id' => 'section-end',
			'type' => 'section',
			'indent' => false,
		),
		array(
			'id' => 'section-start',
			'type' => 'section',
			'title' => esc_html__( 'Menu Typography', 'engage' ),
			'indent' => true,
		),		
		array(
			'id' => 'menu-link',		
			'type' => 'typography',
			'title' => esc_html__( 'Menu Link', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => false,
			'output' => array( ' #snav li a, #main-menu li a, .nav.navbar-nav a'),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '13px',
				'letter-spacing' => '0px',
				'font-weight' => '700',				
				'google' => true,
			),
		),
		array(
			'id' => 'section-end',
			'type' => 'section',
			'indent' => false,
		),
		array(
			'id' => 'section-start',
			'type' => 'section',
			'title' => esc_html__( 'Footer Typography', 'engage' ),
			'indent' => true,
		),	
		array(
			'id' => 'footer',		
			'type' => 'typography',
			'title' => esc_html__( 'Footer Text', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.footer-dark .copyright, .footer-light .copyright'),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '14px',
				'letter-spacing' => '0px',
				'line-height' => '16px',
				'font-weight' => '400',				
				'google' => true,
			),
		),	
		array(
			'id' => 'section-end',
			'type' => 'section',
			'indent' => false,
		),
	)
);


$this->sections[] = array(
	'icon' => 'steadysets-icon-type',
	'title' => esc_html__( 'Special Heading', 'engage' ),
	'heading' => esc_html__( 'Special Heading Typography', 'engage' ),
	'subsection'       => true,
	'fields' => array(
		array(
			'id' => 'sh-upper-title',		
			'type' => 'typography',
			'title' => esc_html__( 'Upper Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.special-heading .upper-title, .special-heading .upper-title.bordered, .special-heading .upper-title.line ' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '14px',
				'letter-spacing' => '0px',
				'line-height' => '14px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
		array(
			'id' => 'sh-title',		
			'type' => 'typography',
			'title' => esc_html__( 'Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.special-heading > h2,.special-heading .upper-title + h2, .special-heading .bordered-title h2,.special-heading .upper-title.bordered + h2, .special-heading .upper-title.line + h2' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '40px',
				'letter-spacing' => '0px',
				'line-height' => '40px',
				'font-weight' => '700',			
				'google' => true,
			),
		),		
	)
);

$this->sections[] = array(
	'icon' => 'steadysets-icon-type',
	'title' => esc_html__( 'Animated Counter', 'engage' ),
	'heading' => esc_html__( 'Animated Counter Typography', 'engage' ),
	'subsection'       => true,
	'fields' => array(		
		array(
			'id' => 'animated-counter-number',		
			'type' => 'typography',
			'title' => esc_html__( 'Counter Number', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.counter .counter-value, .counter.counter-outlined .counter-outline .counter-value' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '70px',
				'letter-spacing' => '0px',
				'line-height' => '70px',
				'font-weight' => '700',				
				'google' => true,
			),
		),
		array(
			'id' => 'animated-counter-upper-title',		
			'type' => 'typography',
			'title' => esc_html__( 'Upper Title', 'engage' ),
			'desc' =>  esc_html__( 'Applied for Box Type Animated Counter', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.counter .counter-title' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '16px',
				'line-height' => '16px',
				'letter-spacing' => '1px',
				'font-weight' => '400',			
				'google' => true,
			),
		),
		array(
			'id' => 'animated-counter-title',		
			'type' => 'typography',
			'title' => esc_html__( 'Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.counter .counter-desc, .counter.counter-outlined .counter-desc' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '14px',
				'line-height' => '25px',
				'letter-spacing' => '1px',
				'font-weight' => '700',			
				'google' => true,
			),
		),		
	)
);


$this->sections[] = array(
	'icon' => 'steadysets-icon-type',
	'title' => esc_html__( 'Animated Icon Box', 'engage' ),
	'heading' => esc_html__( 'Animated Icon Box Typography', 'engage' ),
	'subsection'       => true,
	'fields' => array(			
		array(
			'id' => 'animated-ibox-title',		
			'type' => 'typography',
			'title' => esc_html__( 'Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.animated-icon-box h5' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '16px',
				'line-height' => '17px',
				'letter-spacing' => '0px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
		array(
			'id' => 'animated-ibox-desc',		
			'type' => 'typography',
			'title' => esc_html__( 'Description', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.animated-icon-box p' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '15px',
				'line-height' => '27px',
				'letter-spacing' => '1px',
				'font-weight' => '400',			
				'google' => true,
			),
		),
	)
);		

$this->sections[] = array(
	'icon' => 'steadysets-icon-type',
	'title' => esc_html__( 'Icon Box', 'engage' ),
	'heading' => esc_html__( 'Icon Box Typography', 'engage' ),
	'subsection'       => true,
	'fields' => array(		
		array(
			'id' => 'ibox-title',		
			'type' => 'typography',
			'title' => esc_html__( 'Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.icon-box h3, .icon-box.ibox-small h3, .icon-box.ibox-small.ibox-small-bordered h3, .icon-box.ibox-small.ibox-small-left.ibox-small-bordered h3, .icon-box.ibox-small.ibox-small-right.ibox-small-bordered h3' ), 
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '16px',
				'line-height' => '20px',
				'letter-spacing' => '0px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
		array(
			'id' => 'ibox-desc',		
			'type' => 'typography',
			'title' => esc_html__( 'Description', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.icon-box p' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '13px',
				'line-height' => '22px',
				'letter-spacing' => '1px',
				'font-weight' => '400',			
				'google' => true,
			),
		),		
	)
);

$this->sections[] = array(
	'icon' => 'steadysets-icon-type',
	'title' => esc_html__( 'Featured Image Box', 'engage' ),
	'heading' => esc_html__( 'Featured Image Box Typography', 'engage' ),
	'subsection' => true,
	'fields' => array(		
		array(
			'id' => 'featured-imagebox-title',		
			'type' => 'typography',
			'title' => esc_html__( 'Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.featured-img-box .fimg-box-desc h4, .fancy-box h2' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '18px',
				'line-height' => '18px',
				'letter-spacing' => '0px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
		array(
			'id' => 'featured-imagebox-desc',		
			'type' => 'typography',
			'title' => esc_html__( 'Description', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.fancy-box p, .featured-img-box .fimg-box-desc p, .fancy-box figure.effect-oscar p' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '13px',
				'line-height' => '20px',
				'letter-spacing' => '1px',
				'font-weight' => '400',			
				'google' => true,
			),
		),		
	)
);

$this->sections[] = array(
	'icon' => 'steadysets-icon-type',
	'title' => esc_html__( 'Team', 'engage' ),
	'heading' => esc_html__( 'Team Typography', 'engage' ),
	'subsection'       => true,
	'fields' => array(					
		array(
			'id' => 'team-heading',		
			'type' => 'typography',
			'title' => esc_html__( 'Heading', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.team-title h4' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '16px',
				'line-height' => '16px',
				'letter-spacing' => '0px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
		array(
			'id' => 'team-subheading',		
			'type' => 'typography',
			'title' => esc_html__( 'Sub Heading', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.team-title span' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '13px',
				'line-height' => '13px',
				'letter-spacing' => '1px',
				'font-weight' => '400',			
				'google' => true,
			),
		),
		array(
			'id' => 'teampopup-heading',		
			'type' => 'typography',
			'title' => esc_html__( 'Team Popup Heading', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.member-details h3' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '20px',
				'line-height' => '20px',
				'letter-spacing' => '0px',
				'font-weight' => '700',				
				'google' => true,
			),
		),
		array(
			'id' => 'teampopup-subheading',		
			'type' => 'typography',
			'title' => esc_html__( 'Team Popup Sub Heading', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.member-details p' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '15px',
				'line-height' => '30px',
				'letter-spacing' => '1px',
				'font-weight' => '400',			
				'google' => true,
			),
		),
		array(
			'id' => 'teampopup-skill-title',		
			'type' => 'typography',
			'title' => esc_html__( 'Skill Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.member-details h5' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '16px',
				'line-height' => '16px',
				'letter-spacing' => '0px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
		array(
			'id' => 'teampopup-skill-text',		
			'type' => 'typography',
			'title' => esc_html__( 'Skill Bar text', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.member-details .skill-bar li .skill-name,.member-details .skill-bar li .percentage' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '12px',
				'line-height' => '20px',
				'letter-spacing' => '0px',
				'font-weight' => '400',			
				'google' => true,
			),
		),		
	)
);

$this->sections[] = array(
	'icon' => 'steadysets-icon-type',
	'title' => esc_html__( 'Testimonial Slider', 'engage' ),
	'heading' => esc_html__( 'Testimonial Slider Typography', 'engage' ),
	'subsection'       => true,
	'fields' => array(
		array(
			'id' => 'testimonial-title',		
			'type' => 'typography',			
			'title' => esc_html__( 'Title', 'engage' ),
			'desc' => esc_html__( 'Applicable for testimonial image slider', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.testimonials h3' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '22px',
				'line-height' => '24px',
				'letter-spacing' => '10x',
				'font-weight' => '700',				
				'google' => true,
			),
		),
		array(
			'id' => 'testimonial-text',		
			'type' => 'typography',
			'title' => esc_html__( 'Testimonial text', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.testimonials .slider-content p' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '20px',
				'line-height' => '38px',
				'letter-spacing' => '1px',
				'font-weight' => '300',			
				'google' => true,
			),
		),
		array(
			'id' => 'testimonial-heading',		
			'type' => 'typography',
			'title' => esc_html__( 'Testimonial Author Name', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.testimonials .slider-content h4 ' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '15px',
				'line-height' => '14px',
				'letter-spacing' => '0px',
				'font-weight' => '700',				
				'google' => true,
			),
		),
		array(
			'id' => 'testimonial-subheading',		
			'type' => 'typography',
			'title' => esc_html__( 'Testimonial Author Position', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.testimonials .slider-content div' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '12px',
				'line-height' => '12px',
				'letter-spacing' => '1px',
				'font-weight' => '400',			
				'google' => true,
			),
		),
	)
);


$this->sections[] = array(
	'icon' => 'steadysets-icon-type',
	'title' => esc_html__( 'Pricing', 'engage' ),
	'heading' => esc_html__( 'Pricing Typography', 'engage' ),
	'subsection'       => true,
	'fields' => array(
		array(
			'id' => 'pricing-title',		
			'type' => 'typography',
			'title' => esc_html__( 'Pricing Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.pricing-box.basic .pricing-price-wrap .pricing-title' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '16px',
				'line-height' => '20px',
				'letter-spacing' => '0px',
				'font-weight' => '700',				
				'google' => true,
			),
		),
		array(
			'id' => 'pricing-popular',		
			'type' => 'typography',
			'title' => esc_html__( 'Pricing Popular', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.pricing-box .pricing-popular' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '16px',
				'line-height' => '20px',
				'letter-spacing' => '0px',
				'font-weight' => '700',				
				'google' => true,
			),
		),
		array(
			'id' => 'pricing-unit',		
			'type' => 'typography',
			'title' => esc_html__( 'Pricing Currency', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.pricing-box .pricing-price-wrap .pricing-unit' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'raleway',
				'font-size' => '25px',
				'line-height' => '25px',
				'letter-spacing' => '0px',
				'font-weight' => '600',				
				'google' => true,
			),
		),
		array(
			'id' => 'pricing-price',		
			'type' => 'typography',
			'title' => esc_html__( 'Pricing Price', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.pricing-box .pricing-price-wrap .pricing-price' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '70px',
				'line-height' => '70px',
				'letter-spacing' => '0px',
				'font-weight' => '700',				
				'google' => true,
			),
		),
		array(
			'id' => 'pricing-tenure',		
			'type' => 'typography',
			'title' => esc_html__( 'Pricing Tenure', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.pricing-box .pricing-price-wrap .pricing-tenure' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '13px',
				'line-height' => '20px',
				'letter-spacing' => '0px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
		array(
			'id' => 'pricing-features',		
			'type' => 'typography',
			'title' => esc_html__( 'Pricing Features', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.pricing-box ul li' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '13px',
				'line-height' => '16px',
				'letter-spacing' => '1px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
	)
);

$this->sections[] = array(
	'icon' => 'steadysets-icon-type',
	'title' => esc_html__( 'Address Block', 'engage' ),
	'heading' => esc_html__( 'Address Block Typography', 'engage' ),
	'subsection'       => true,
	'fields' => array(
		array(
			'id' => 'address-title',		
			'type' => 'typography',
			'title' => esc_html__( 'Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.contact-info-wrap .contact-info-item div strong' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '14px',
				'letter-spacing' => '0px',
				'line-height' => '22px',
				'font-weight' => '700',				
				'google' => true,
			),
		),	
		array(
			'id' => 'address-desc',		
			'type' => 'typography',
			'title' => esc_html__( 'Description', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.contact-info-item div.contact-desc, .contact-info-item div.contact-desc span.number, .contact-info-item div.contact-desc a,.contact-info-wrap .contact-info-item div:last-child ' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '13px',
				'letter-spacing' => '1px',
				'line-height' => '22px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
	)
);

$this->sections[] = array(
	'icon' => 'steadysets-icon-type',
	'title' => esc_html__( 'Mailchimp', 'engage' ),
	'heading' => esc_html__( 'Mailchimp Typography', 'engage' ),
	'subsection' => true,
	'fields' => array(
		array(
			'id' => 'mailchimp-heading',		
			'type' => 'typography',
			'title' => esc_html__( 'Heading', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.widget-subscribe-form p,.widget-subscribe-form div i' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '17px',
				'letter-spacing' => '1px',
				'line-height' => '17px',
				'font-weight' => '400',				
				'google' => true,
			),
		),	
		array(
			'id' => 'mailchimp-subheading',		
			'type' => 'typography',
			'title' => esc_html__( 'Sub Heading', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.widget-subscribe-form > h2' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '30px',
				'letter-spacing' => '0px',
				'line-height' => '26px',
				'font-weight' => '700',				
				'google' => true,
			),
		),
		array(
			'id' => 'mailchimp-description',		
			'type' => 'typography',
			'title' => esc_html__( 'Description', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.widget-subscribe-form > div' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '15px',
				'letter-spacing' => '1px',
				'line-height' => '16px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
	)
);
$this->sections[] = array(
	'icon' => 'steadysets-icon-type',
	'title' => esc_html__( 'Twitter', 'engage' ),
	'heading' => esc_html__( 'Twitter Typography', 'engage' ),
	'subsection' => true,
	'fields' => array(
		array(
			'id' => 'tweet-heading',		
			'type' => 'typography',
			'title' => esc_html__( 'Tweet Heading', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.tweets > u' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Montserrat',
				'font-size' => '16px',
				'letter-spacing' => '0px',
				'line-height' => '34px',
				'font-weight' => '400',				
				'google' => true,
			),
		),	
		array(
			'id' => 'tweet-text',		
			'type' => 'typography',
			'title' => esc_html__( 'Tweet Text', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.tweets > div div p' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '20px',
				'letter-spacing' => '0px',
				'line-height' => '34px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
		array(
			'id' => 'tweet-footer',		
			'type' => 'typography',
			'title' => esc_html__( 'Tweet Date', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.golo-carousel u, .golo-carousel u, .no-carousel u ,.no-carousel u' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '16px',
				'letter-spacing' => '0px',
				'line-height' => '34px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
	)
);
$this->sections[] = array(
	'icon' => 'steadysets-icon-type',
	'title' => esc_html__( 'Call To Action', 'engage' ),
	'heading' => esc_html__( 'Call To Action Typography', 'engage' ),
	'subsection' => true,
	'fields' => array(
		array(
			'id' => 'cta-heading',		
			'type' => 'typography',
			'title' => esc_html__( 'Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.promo h2' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Montserrat',
				'font-size' => '32px',
				'letter-spacing' => '0px',
				'line-height' => '32px',
				'font-weight' => '700',				
				'google' => true,
			),
		),	
		array(
			'id' => 'cta-subheading',		
			'type' => 'typography',
			'title' => esc_html__( 'Sub Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.promo p' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'Raleway',
				'font-size' => '16px',
				'letter-spacing' => '0px',
				'line-height' => '25px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
		array(
			'id' => 'cta-list',		
			'type' => 'typography',
			'title' => esc_html__( 'List Item', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.promo.extended .promo-list-item li' ),
			'units' => 'px',
			'default' => array(
				'font-family' => 'raleway',
				'font-size' => '13px',
				'letter-spacing' => '0px',
				'line-height' => '13px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
	)
);


$this->sections[] = array(
	'icon' => 'steadysets-icon-type',
	'title' => esc_html__( 'Button', 'engage' ),
	'heading' => esc_html__( 'Button Typography', 'engage' ),
	'subsection'       => true,
	'fields' => array(
		array(
			'id' => 'button',		
			'type' => 'typography',
			'title' => esc_html__( 'Button Text', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.btn'),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '12px',
				'letter-spacing' => '0px',
				'line-height' => '20px',
				'font-weight' => '400',				
				'google' => true,
			),
		),	
		array(
			'id' => 'contact-button',		
			'type' => 'typography',
			'title' => esc_html__( 'Contact Button Text', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.wpcf7-form p input[type="submit"], .wpcf7-form p.outlined input[type="submit"] '),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '14px',
				'letter-spacing' => '1px',
				'line-height' => '14px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
	)
);
$this->sections[] = array(
	'icon' => 'steadysets-icon-type',
	'title' => esc_html__( 'Blog Grid', 'engage' ),
	'heading' => esc_html__( 'Blog Grid Typography', 'engage' ),
	'subsection' => true,
	'fields' => array(
		array(
			'id' => 'post-date',		
			'type' => 'typography',
			'title' => esc_html__( 'Post Date', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.entry .entry-meta li '),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '12px',
				'letter-spacing' => '0px',
				'line-height' => '18px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
		array(
			'id' => 'post-title',		
			'type' => 'typography',
			'title' => esc_html__( 'Post Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.entry .entry-title h3'),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '24px',
				'letter-spacing' => '0px',
				'line-height' => '34px',
				'font-weight' => '700',				
				'google' => true,
			),
		),	
		array(
			'id' => 'post-text',		
			'type' => 'typography',
			'title' => esc_html__( 'Post Text', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.entry .entry-content p'),
			'units' => 'px',
			'default' => array(
				'font-family' => 'raleway',
				'font-size' => '14px',
				'letter-spacing' => '0px',
				'line-height' => '25px',
				'font-weight' => '400',				
				'google' => true,
			),
		),	
		array(
			'id' => 'post-link',		
			'type' => 'typography',
			'title' => esc_html__( 'Post Link', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.entry .more-link'),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '13px',
				'letter-spacing' => '0px',
				'line-height' => '28px',
				'font-weight' => '400',				
				'google' => true,
			),
		),	
	)
);
$this->sections[] = array(
	'icon' => 'steadysets-icon-type',
	'title' => esc_html__( 'Portfolio', 'engage' ),
	'heading' => esc_html__( 'Portfolio Typography', 'engage' ),
	'subsection'       => true,
	'fields' => array(
		array(
			'id' => 'portfolio-filter',		
			'type' => 'typography',
			'title' => esc_html__( 'Portfolio Filter', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.cbp-l-filters-alignLeft .cbp-filter-item, .cbp-l-filters-alignRight .cbp-filter-item, .cbp-l-filters-alignCenter .cbp-filter-item'),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '13px',
				'letter-spacing' => '0px',
				'line-height' => '22px',
				'font-weight' => '400',				
				'google' => true,
			),
		),	
		array(
			'id' => 'portfolio-title',		
			'type' => 'typography',
			'title' => esc_html__( 'Portfolio Caption Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.cbp-l-caption-title '),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '16px',
				'letter-spacing' => '0px',
				'line-height' => '21px',
				'font-weight' => '400',				
				'google' => true,
			),
		),	
		array(
			'id' => 'portfolio-subtitle',		
			'type' => 'typography',
			'title' => esc_html__( 'Portfolio Caption Sub Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.cbp-l-caption-desc'),
			'units' => 'px',
			'default' => array(
				'font-family' => 'raleway',
				'font-size' => '12px',
				'letter-spacing' => '0px',
				'line-height' => '16px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
		array(
			'id' => 'lightbox-title',		
			'type' => 'typography',
			'title' => esc_html__( 'Lightbox Title & Counter', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.cbp-popup-lightbox-title, .cbp-popup-lightbox-counter'),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '12px',
				'letter-spacing' => '0px',
				'line-height' => '18px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
		array(
			'id' => 'singlepage-counter',		
			'type' => 'typography',
			'title' => esc_html__( 'Single Page Counter', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.cbp-popup-singlePage-counter'),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '16px',
				'letter-spacing' => '0px',
				'line-height' => '30px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
		array(
			'id' => 'singlepage-title',		
			'type' => 'typography',
			'title' => esc_html__( 'Single Page Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.cbp-l-project-title'),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '42px',
				'letter-spacing' => '0px',
				'line-height' => '46px',
				'font-weight' => '700',				
				'google' => true,
			),
		),
		array(
			'id' => 'singlepage-subtitle',		
			'type' => 'typography',
			'title' => esc_html__( 'Single Sub Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.cbp-l-project-subtitle'),
			'units' => 'px',
			'default' => array(
				'font-family' => 'raleway',
				'font-size' => '14px',
				'letter-spacing' => '1px',
				'line-height' => '21px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
		array(
			'id' => 'single-page-desc-title',		
			'type' => 'typography',
			'title' => esc_html__( 'Single Page Content Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.cbp-l-project-desc-title span, .cbp-l-project-details-title span, .cbp-l-project-desc-title span  '),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '19px',
				'letter-spacing' => '0px',
				'line-height' => '50px',
				'font-weight' => '700',				
				'google' => true,
			),
		),
		array(
			'id' => 'related-title',		
			'type' => 'typography',
			'title' => esc_html__( 'Single Page Related Projects Title', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.cbp-l-project-related-title'),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '15px',
				'letter-spacing' => '0px',
				'line-height' => '18px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
		array(
			'id' => 'single-page-list',		
			'type' => 'typography',
			'title' => esc_html__( 'Single Page List Item', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.cbp-l-project-details-list > div, .cbp-l-project-details-list > li, .cbp-l-project-details-list strong'),
			'units' => 'px',
			'default' => array(
				'font-family' => 'montserrat',
				'font-size' => '13px',
				'letter-spacing' => '0px',
				'line-height' => '30px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
		array(
			'id' => 'single-page-desc',		
			'type' => 'typography',
			'title' => esc_html__( 'Single Page Description ', 'engage' ),
			'google' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => true,
			'line-height' => true,
			'output' => array( '.cbp-l-project-desc-text p'),
			'units' => 'px',
			'default' => array(
				'font-family' => 'raleway',
				'font-size' => '14px',
				'letter-spacing' => '1px',
				'line-height' => '28px',
				'font-weight' => '400',				
				'google' => true,
			),
		),
	)
);

  